import { useEffect, useState } from "react"; import { Link } from "react-router-dom"; import { Users, GitBranch, HeartHandshake, CalendarDays, ArrowRight, UserRoundPlus, ImagePlus, Mail, Leaf } from "lucide-react"; import { api } from "../lib/api";
export function DashboardPage({ user, tree }) {
    const [d, setD] = useState(null), [error, setError] = useState(""); useEffect(() => { api.get("/dashboard").then(r => setD(r.data.data)).catch(e => setError(e.response?.data?.message || "Unable to load your family story.")) }, []);
    if (error) return <div className="feature-page"><div className="error-state"><h2>We couldn't load your dashboard.</h2><p>{error}</p><button className="primary" onClick={() => location.reload()}>Try again</button></div></div>;
    return <div className="dashboard-page"><section className="hero-card"><div className="hero-copy"><span className="hero-kicker"><Leaf size={14} /> FAMILYROOTS</span><h1>Your family story deserves to be remembered.</h1><p>Welcome back, {user?.name?.split(" ")[0]}. Build, preserve and explore your family history — together.</p><div className="hero-actions"><Link className="primary" to="/tree">View family tree <ArrowRight size={17} /></Link><Link className="secondary" to="/members">Explore members</Link></div></div><div className="hero-art" aria-hidden="true"><div className="art-ring ring-a" /><div className="art-ring ring-b" /><Leaf size={96} /><span>Our Family<br /><b>Our Story</b></span></div></section>
        <div className="section-heading"><div><p className="eyebrow">YOUR FAMILY STORY</p><h2>{tree?.name || "Your Family Tree"}</h2></div><span className="status-pill">Private & secure</span></div>
        <div className="stat-grid">{[["Members", d?.stats.members, Users], ["Generations", d?.stats.generations, GitBranch], ["Relationships", d?.stats.relationships, HeartHandshake], ["Collaborators", d?.stats.collaborators, Users]].map(([label, value, Icon]) => <div className="stat-card" key={label}><span className="stat-icon"><Icon size={18} /></span><div><b>{value ?? "—"}</b><span>{label}</span></div></div>)}</div>
        <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">RECENT HISTORY</p><h3>Recent family activity</h3></div><Link to="/events">View all <ArrowRight size={14} /></Link></div>{d?.events?.length ? <div className="activity-list">{d.events.map(e => <div className="activity" key={e._id}><span className="activity-date">{new Date(e.date).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</span><div><b>{e.title}</b><p>{e.member?.fullName || "Family event"} · {e.type}</p></div></div>)}</div> : <div className="inline-empty"><CalendarDays size={22} /><span>No family events yet. <Link to="/events">Add an important moment.</Link></span></div>}</section>
            <section className="panel quick-panel"><p className="eyebrow">QUICK ACTIONS</p><h3>Keep the story growing</h3><div className="quick-actions"><Link to="/tree"><GitBranch /><span><b>View Family Tree</b><small>Explore your connections</small></span><ArrowRight /></Link><Link to="/members"><UserRoundPlus /><span><b>Add Family Member</b><small>Grow your family tree</small></span><ArrowRight /></Link><Link to="/settings"><Mail /><span><b>Invite Family Member</b><small>Build together</small></span><ArrowRight /></Link><Link to="/gallery"><ImagePlus /><span><b>Explore Memories</b><small>Preserve the moments</small></span><ArrowRight /></Link></div></section></div></div>
}
